CONST_ANGLE_ACCURACY = 5
CONST_SPEED_FACTOR = 0.1
CONST_MIN_PWM = 0
CONST_MAX_PWM = 1023

CONST_CLAW_PORT = 0
CONST_CLAW_CLOSED = 300
CONST_CLAW_OPEN = 450

CONST_SEGMENT_MOTOR_PORTS = [4,5,6]
CONST_ROTATOR_PORT = 3
